// src/pages/Dashboard.vue
<script setup lang="ts">
import { ref, onMounted, watchEffect } from 'vue'
import { supabase } from '@/integrations/supabase/client'
import { useAuth } from '@/composables/useAuth'
import { Button } from '@/components/ui/button/index'

type Booking = { 
  id: number 
  booking_date: string 
  booking_time: string 
  status: string 
  services: { name: string; price: number } | null 
}

type Order = { 
  id: number 
  total_amount: number 
  status: string 
  created_at: string 
}

const { user, loading } = useAuth()
const bookings = ref<Booking[]>([])
const orders = ref<Order[]>([])

watchEffect(async () => {
  if (!user.value) return
  
  // Fetch the public user ID (integer)
  const { data: publicUser } = await supabase
    .from('users')
    .select('id')
    .eq('email', user.value.email)
    .single()
    
  if (!publicUser) return

  const { data: bookingsData } = await supabase
    .from('bookings')
    .select('id,booking_date,booking_time,status,services(name,price)')
    .eq('user_id', publicUser.id)
    .order('booking_date', { ascending: false })
  
  if (bookingsData) {
    bookings.value = bookingsData as unknown as Booking[]
  }
  
  const { data: ordersData } = await supabase
    .from('orders')
    .select('*')
    .eq('user_id', publicUser.id)
    .order('created_at', { ascending: false })
  
  if (ordersData) {
    orders.value = ordersData as Order[]
  }
})

const getStatusBadgeClass = (status: string) => {
  if (status === 'completed') return 'bg-green-100 text-green-700'
  if (status === 'confirmed') return 'bg-blue-100 text-blue-700'
  return 'bg-amber-100 text-amber-700'
}
</script>

<template>
  <div v-if="!loading" class="container mx-auto max-w-3xl px-4 py-12">
    <div v-if="!user" class="max-w-md mx-auto text-center">
      <p class="text-muted-foreground">Please sign in to view your dashboard.</p>
      <router-link to="/auth">
        <Button class="mt-4">Sign in</Button>
      </router-link>
    </div>
    
    <template v-else>
      <h1 class="font-serif text-3xl font-bold">My Account</h1>
      <p class="mt-1 text-sm text-muted-foreground">{{ user.email }}</p>

      <section class="mt-8">
        <h2 class="font-serif text-xl font-semibold">My Bookings</h2>
        <div class="mt-3 space-y-2">
          <p v-if="bookings.length === 0" class="text-sm text-muted-foreground">No bookings yet.</p>
          <div 
            v-for="b in bookings" 
            :key="b.id" 
            class="flex items-center justify-between rounded-xl border border-border bg-card p-4"
          >
            <div>
              <p class="font-medium">{{ b.services?.name ?? "Service" }}</p>
              <p class="text-xs text-muted-foreground">{{ b.booking_date }} at {{ b.booking_time }}</p>
            </div>
            <span :class="['rounded-full px-3 py-1 text-xs font-medium', getStatusBadgeClass(b.status)]">
              {{ b.status }}
            </span>
          </div>
        </div>
      </section>

      <section class="mt-8">
        <h2 class="font-serif text-xl font-semibold">My Orders</h2>
        <div class="mt-3 space-y-2">
          <p v-if="orders.length === 0" class="text-sm text-muted-foreground">No orders yet.</p>
          <div 
            v-for="o in orders" 
            :key="o.id" 
            class="flex items-center justify-between rounded-xl border border-border bg-card p-4"
          >
            <div>
              <p class="font-medium">KES {{ o.total_amount }}</p>
              <p class="text-xs text-muted-foreground">{{ new Date(o.created_at).toLocaleDateString() }}</p>
            </div>
            <span :class="['rounded-full px-3 py-1 text-xs font-medium', getStatusBadgeClass(o.status)]">
              {{ o.status }}
            </span>
          </div>
        </div>
      </section>
    </template>
  </div>
</template>

// src/routes/dashboard.tsx
import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/auth";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/dashboard")({ component: Dashboard });

type Booking = { id: string; booking_date: string; booking_time: string; status: string; services: { name: string; price: number } | null };
type Order = { id: string; total_amount: number; status: string; created_at: string };

function Dashboard() {
  const { user, loading } = useAuth();
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [orders, setOrders] = useState<Order[]>([]);

  useEffect(() => {
    if (!user) return;
    supabase.from("bookings").select("id,booking_date,booking_time,status,services(name,price)").eq("user_id", user.id).order("booking_date", { ascending: false })
      .then(({ data }) => data && setBookings(data as unknown as Booking[]));
    supabase.from("orders").select("*").eq("user_id", user.id).order("created_at", { ascending: false })
      .then(({ data }) => data && setOrders(data as Order[]));
  }, [user]);

  if (loading) return null;
  if (!user) {
    return (
      <div className="container mx-auto max-w-md px-4 py-12 text-center">
        <p className="text-muted-foreground">Please sign in to view your dashboard.</p>
        <Link to="/auth"><Button className="mt-4">Sign in</Button></Link>
      </div>
    );
  }

  return (
    <div className="container mx-auto max-w-3xl px-4 py-12">
      <h1 className="font-serif text-3xl font-bold">My Account</h1>
      <p className="mt-1 text-sm text-muted-foreground">{user.email}</p>

      <section className="mt-8">
        <h2 className="font-serif text-xl font-semibold">My Bookings</h2>
        <div className="mt-3 space-y-2">
          {bookings.length === 0 && <p className="text-sm text-muted-foreground">No bookings yet.</p>}
          {bookings.map((b) => (
            <div key={b.id} className="flex items-center justify-between rounded-xl border border-border bg-card p-4">
              <div>
                <p className="font-medium">{b.services?.name ?? "Service"}</p>
                <p className="text-xs text-muted-foreground">{b.booking_date} at {b.booking_time}</p>
              </div>
              <StatusBadge status={b.status} />
            </div>
          ))}
        </div>
      </section>

      <section className="mt-8">
        <h2 className="font-serif text-xl font-semibold">My Orders</h2>
        <div className="mt-3 space-y-2">
          {orders.length === 0 && <p className="text-sm text-muted-foreground">No orders yet.</p>}
          {orders.map((o) => (
            <div key={o.id} className="flex items-center justify-between rounded-xl border border-border bg-card p-4">
              <div>
                <p className="font-medium">KES {o.total_amount}</p>
                <p className="text-xs text-muted-foreground">{new Date(o.created_at).toLocaleDateString()}</p>
              </div>
              <StatusBadge status={o.status} />
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}

function StatusBadge({ status }: { status: string }) {
  const cls = status === "completed" ? "bg-green-100 text-green-700"
    : status === "confirmed" ? "bg-blue-100 text-blue-700"
    : "bg-amber-100 text-amber-700";
  return <span className={`rounded-full px-3 py-1 text-xs font-medium ${cls}`}>{status}</span>;
}
